"""updated files table

Revision ID: fcf94258e4de
Revises: 0f9b07d39935
Create Date: 2025-05-04 16:35:54.660032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf94258e4de'
down_revision: Union[str, None] = '0f9b07d39935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_name', sa.String(), nullable=False))
    op.add_column('files', sa.Column('date_associated', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'date_associated')
    op.drop_column('files', 'file_name')
    # ### end Alembic commands ###
